SUDO: required
services:
  - docker

before_install:
  - docker build -t hmanoj59/multi-docker-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true hmanoj59/multi-docker-test npm test

after_success:
  - docker build -t hmanoj59/multi-client -f ./client
  - docker build -t hmanoj59/multi-nginx -f ./nginx
  - docker build -t hmanoj59/multi-server -f ./server
  - docker build -t hmanoj59/multi-worker -f ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push hmanoj59/multi-client
  - docker push hmanoj59/multi-nginx
  - docker push hmanoj59/multi-server
  - docker push hmanoj59/multi-worker
